 channels:
     - conda-forge
 dependencies:
     - dlib
     - numpy
     - scipy
     - opencv_python
     - face_recognition
     - imutils
     - openpyxl
     - pandas
     - Pillow
     - streamlit
     - XlsxWriter